### ISSUE TITLE
iOS document picker support

### ISSUE THREAD

**Issue by palmin** [larki/VimIOS#3]
This is a really impressive project. I have not heard about it before now, because I am more of the Emacs<sup>1</sup> type. Many people I know, including my brother, love having a nice vim on iOS.

I am the developer of [Working Copy](https://WorkingCopyApp.com/) and I would like to offer my help implementing document picker support, knowing a lot about this API on the iOS side. 

My weakness is limited vim knowledge. I am not sure what the best command would be to invoke the document picker or how to persist the files or directories the user has previously picked.

There are 3 steps to having full document picker support, that I can help with:
1. Invoke the [document picker](UIDocumentPickerViewController) with UIDocumentPickerModeOpen to open either a file or directory. The result is a file-schemed url.
2. When reading, writing files or creating files everything must be done under [file coordination](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileCoordinators/FileCoordinators.html).
3. The file-schemed URLs are [security scoped](https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16) and must be stored in a certain way.

You should not need to use UIDocument even though it wraps some of the things above.

[1] a little afraid to mention this, please be gentle

**Comment by larki** [comment]
Hi Anders,

I am happy you like the project! The vim port is indeed impressive but unfortunately not my work. I just updated it to make it iOS 9 compatible, and I added some hacks to make it more usable with an external keyboard (by default Apple does not allow keys to "repeat" when you hold them down. Luckily I found a hack around it, I hope they don’t close the loop hole.)

My knowledge of vim source is also very limited, and to me it seems very messy.

When I thought about implementing document picker support, my rough plan looked like this:
1) The port uses vim’s inbuilt facility to write and read files. This would be very complicated to replace, I fear.
2) To open a document from the document picker, the user invokes something like ":DocumentPicker" from inside vim. This would be a command that we would have to define. It should call iOS’ document picker, and then produce some file which vim can open with its own facilities.
3) To write to a file coming from the document picker, the user does not invoke ":w" as usual, but rather some other command that we would have to define, say ":WriteDocument". Again, this would be a custom command, which first writes the file to the file provided by the document picker, and then calls whatever iOS function needs to be called to update the file coordination
4) Potential problems: I am not sure how we could handle the situation in which the user switches to a different app without saving the file first.
5) If this works really well, we could replace the standard ":e" and ":w" commands.

**Comment by palmin** [comment]
Your plan sounds sensible. 

Could you point me in the right direction to where new commands are added? Where should I start looking?

Regarding (4) how is this handled for regular files? Is there some kind of temporary file that holds the current file changes or do you just loose changes if you switch away without saving and iOS determines to terminate the app?

**Comment by larki** [comment]
The new commands are defined in Vim’s scripting language in the .vimrc which is in the project. There you can find for example the commands that I defined to invoke iOS’s share sheet.
Vim provides some functions to interact with the operating system, which I "misuse":
- For the share sheet I use the ":browse" command which is supposed to call a file selection dialog from the operating system. When you execute ":browse" in Vim, the function gui_mch_browse from gui_ios.c is called. It does some work and then calls showShareSheetForURL on the ViewController
- and for emailing a file, I use the vim function "confirm" which is supposed to create a modal dialog. Calls gui_mch_dialog in gui_ios.c which in turn calls the ShowShareSheetForURL on the view controller.

This way I did not have to actually change anything in the vim code to get some interaction with iOS.

(4)As in true vim fashion, if you don’t save your file, it’s gone. Vim writes directly to the iOS file system. You can do ":e ." do "browse" the local file system. I suppose this is a behavior that apple wouldn’t be so happy about...

Best,
Lars

**Comment by palmin** [comment]
Regarding (4) I think this is a pretty bad bug and should not be seen as saving files as much as state restoration.

I agree content should not be written to the file unless you specifically save, but editor content is something the user expects is kept around until they discard it themselves. That you switch to some other app and then back, is not something the user should worry about. Users would even get away with it sometimes, but at other times, when there are memory constraints, they would loose edits.

But it has nothing to do with this document picker as such and I will not spend more time arguing it. 

I have forked the project and will dig into it. Will probably ask for details on how best to do stuff here.

**Comment by xslim** [comment]
Here is a demo of picking up files I made: https://github.com/xslim/DPTest

I also ported this project to Swift 3, now working on implementing this feature

**Comment by xslim** [comment]
So in current implementation, when you trigger command `:Share`, it actually goes to `:browse save`.
For Document picker, I'm using `:browse open`.  Then I am sending the URL to file / folder to the `:edit` command.

Do you think it is the correct approach?

**Comment by larki** [comment]
Hi, yes I think that is a good approach, because this seems to be the easiest way to communicate with vim proper, without having to modify the vim source directly.

**Comment by xslim** [comment]
So I'm trying to implement this `NSFileCoordinator`, but can't figure out how to properly do it:
- currently, I'm calling `NSFileCoordinator.addFilePresenter(self)` in `viewDidLoad`, then I'm doing this:

``` swift
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentAt url: URL) {
        let fc = NSFileCoordinator()
        fc.coordinate(readingItemAt: url, options: .withoutChanges, error: nil) {
            ( newURL : URL!) -> Void  in
            let path = newURL.relativePath.replacingOccurrences(of: " ", with: "\\ ")
            print("new url: \(path)")
            do_cmdline_cmd(":edit \(path)")
        }
    }
```

Now sometimes Vim shows "Permission denied" on some apps, and on other (iCloud Drive) it shows that this file can be probably edited by another application, but still opens it.

Any ideas?

**Comment by palmin** [comment]
You should make sure and call startAccessingSecurityScopedResource on the url.

**Comment by xslim** [comment]
Well here is the first working prototype: https://github.com/xslim/VimIOS/commit/627f6fa280a09dc171d2533fb71e0e917cbac880
- short cut command `:DP` (triggers `:browse open`) - configured in vimrc
- disable creating swap files and backups
- `:Share` and `:browse save` will still work

TODO:
- figure out when to call `stopAccessingSecurityScopedResource`
- anything else needed to do with `NSFilePresenter` ?
- `do_cmdline_cmd("edit \(path)")` does not executes it - you still need to press Enter key - any idea why?

**Comment by xslim** [comment]
@palmin Is there any good example how to use the File coordination, file presenting and url security scoping? Can't find anything good online.

Should I call `stopAccessingSecurityScopedResource` right after opening the file in Vim?
But then what to do when I will write? Trigger `start` again?

@larki Any idea how can I get a callback when Vim will start/stop writing to file?

**Comment by palmin** [comment]
I do not know of any good examples, unfortunately. I can quickly write out how I understand file coordinators and file presenters. 

File coordinators are used for specific file actions. File presenters are used to indicate that you have something going on with a file, something long term. A file presenter can be told when there are changes to a file, but will also be asked to write out the changes it has itself, if some other presenter might need these.

The magic of file coordination happens when there are multiple presenters for the same file. The OS will help make sure changes are written to the file and read in by the other presenter. But with vim that has manuel save, I do not think we need to worry about this.

It would totally make sense to wrap any loading/saving in startAccessingSecurityScopedResource + stopAccessingSecurityScopedResource. 

Not sure if needed, but if a security scoped URL needs to be persisted and available when the app opens again, it is not sufficient to just store the URL.

**Comment by larki** [comment]
@xslim To get a callback before/after writing to a file, the best thing I can think of is using autocommands. The relevant autocommands seem to be:
```
BufWritePre		starting to write the whole buffer to a file
BufWritePost		after writing the whole buffer to a file
BufWriteCmd		before writing the whole buffer to a file Cmd-event

FileWritePre		starting to write part of a buffer to a file
FileWritePost		after writing part of a buffer to a file
```

see e.g. [here](http://stackoverflow.com/questions/4627701/vim-how-to-execute-automatically-execute-a-shell-command-after-saving-a-file) for an example application.

**Comment by xslim** [comment]
Well we need to trigger the callback in the code somehow.
is there any `gui_mch_` (or similar) callback that you know that could be triggered in `gui_ios.m` ?

**Comment by larki** [comment]
Not off the top of my hat, I will have a look tonight.

**Comment by xslim** [comment]
With my patch https://github.com/xslim/VimIOS/commit/627f6fa280a09dc171d2533fb71e0e917cbac880 I am able to edit file and see that it's content changed in other app after saving, but I can't open the folder - it's just shown as empty... figuring out why...

**Comment by mtwebb** [comment]
Just chiming in that this project is fantastic.  I've been itching for native vim on iPad since iPad Pro.  Touch screen txt selection is just so slow and fiddly that keyboard based text manipulation makes perfect sense.  Felt so good to fire it up on iPad Pro tonight.   

Do you need iCloud entitlements for the proper file document browser to function?   I stripped them out of VimIOS.entitlements so I could load from my free account, but happy to rejoin if it adds that functionality back in.

**Comment by larki** [comment]
As far as I can see, even with the correct iCloud entitlements, there is no working integration with the iOS file browsing facilities yet.

**Comment by mtwebb** [comment]
Today's keynote announcements for the Files app feels like a big step in the right direction for making vim on iPad useful.

**Comment by hggz** [comment]
Just dropping in to say thanks for working on this! Ive followed that vim port for like 2 years and was hoping to get time to try working on a suitable port! With that being said, I noticed there was some rendering issues on iOS 10.3.1. Is anyone else aware of that?

**Comment by palmin** [comment]
I have had questions about this from a few people and decided to write a small Swift app that shows how to handle many of these details when opening files or directories in-place with the document picker.

https://github.com/palmin/open-in-place

**Comment by mtwebb** [comment]
One step ahead @palmin .

I just came to link to Apple's landing page for Document based apps: 
https://developer.apple.com/document-based-apps/
